language: python
dist: xenial 
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - python Framework/HtmlData.py
  - python Framework/PyHtml.py
  - python Framework/CssTool.py
  - python main.py
  - Project/projectFile.py
before_install:
  - chmod +x Example/index.html
branches:
  - master
